### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by Abdelmounaim18** [mawaqit-foundation/home-assistant-component#9]
Hello,

I was using this addon with no problems for a couple of months now. Until recently when my prayer sensors in home assistant became unavailable. I tried removing the integration and setting it up again, but when logging in I am getting “**unknown error occurred**”. I even tried making a new account at Mawaqit, unfortunately it didn’t help either.  I hope there is a fix for this because it was really useful.

**This is the error in the logs:**

> 2021-05-17 12:22:18 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for mawaqit doing I/O at custom_components/mawaqit/config_flow.py, line 87: response = get(url, auth=(username, password))

> RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/mawaqit/config_flow.py, line 87: response = get(url, auth=(username, password))

**This is the login screen error:**
![IMG_3939](https://user-images.githubusercontent.com/44317217/118473950-d4a3e980-b70a-11eb-86b1-e65dc6a11c8b.jpeg)

**Comment by ibrahim-zehhaf** [comment]
@yac69 this bug is related to the new version of hassio ?

**Comment by yac69** [comment]
Indeed, a recent update of hassio has broken many addins including the mawaqit one. I am actively trying to figure out the issue. I already created a python library of mawaqit that I submitted to pypi. then the new version of the addon will rely on this new python library. 
I started revisong the hassio mawaqit addon. I am struggling with the mosque choice given to the user when adding the integration.

**Comment by ibrahim-zehhaf** [comment]
Thanks @yac69 🙏🏻

**Comment by Abdelmounaim18** [comment]
@yac69 That sounds good, I'll wait for the patch then. Thanks for doing this!

**Comment by yac69** [comment]
@Abdelmounaim18 @ibrahim-zehhaf 
I just uploaded v2. Can you please check and report any issue.
Barak Allah fikom

**Comment by yac69** [comment]
ideally, get ride of the previous version and start from scratch. for this purpose remove the mawaqit folder of the custom_components of hassio. no need to change automations and other yaml file

**Comment by Abdelmounaim18** [comment]
I'll try it in a moment inchaAllah, I let you know if it worked.

**Comment by Abdelmounaim18** [comment]
@yac69 I have tested it and it is working again! Thank you for the quick fix, **Jazāk Allāhu Khayran**.

**Comment by yac69** [comment]
Barak Allah Fik @Abdelmounaim18

**Comment by ibra-iad** [comment]
GG @yac69 and thanks @Abdelmounaim18 for testing.
@yac69 it would be even better, if the addon update the data regularly to take updates into account, because the manager of the mosque can change/adjust the timetable

**Comment by yac69** [comment]
> GG @yac69 and thanks @Abdelmounaim18 for testing.
> @yac69 it would be even better, if the addon update the data regularly to take updates into account, because the manager of the mosque can change/adjust the timetable

Yes this is the case. The data on Salat time are updated once a day. And the mosque data every hour that we can change to any frequency in the sensor.py file. I will comment the later to indicate where to do it

**Comment by ibrahim-zehhaf** [comment]
good thanks
